name: widgetbook
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_treeview: ^1.0.6+1
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  recase: ^4.0.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - google_fonts/
