name: widgetbook_models
description: A new Flutter package project.
version: 0.0.1
homepage: 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  meta: ^1.7.0

dev_dependencies:
  test: ^1.18.2
  very_good_analysis: ^2.3.0