name: widgetbook_cli
description: A command-line application to upload Widgetbook builds to Widgetbook Cloud.
version: 2.0.0-beta.1
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_models
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_cli

environment:
  sdk: '>=2.17.0 <3.0.0'


dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lints: ^1.0.0
  very_good_analysis: ^3.0.0
dependencies: 
  archive: ^3.3.0
  args: ^2.3.0
  dio: ^4.0.6
  file: ^6.1.2
  freezed_annotation: ^2.0.3
  widgetbook_git: ^2.1.0 
  http_parser: ^4.0.1
  path: ^1.8.2
  test: ^1.12.1 
  version: ^2.0.0
