name: widgetbook
description: A flutter storybook that helps professionals and teams to catalog their widgets.
version: 0.0.1
homepage: https://firecrown.pro
repository: https://github.com/firecrownpro/widgetbook
issue_tracker: https://github.com/firecrownpro/widgetbook/issues 
# documentation: https://firecrown.pro 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_treeview: ^1.0.6+1
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  recase: ^4.0.0
  url_launcher: ^6.0.9
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - google_fonts/
