name: widgetbook
description: A flutter storybook that helps professionals and teams to catalogue their widgets.
version: 0.0.9
homepage: https://firecrown.pro?utm_source=pub.dev&utm_medium=link&utm_campaign=package_widgetbook
repository: https://github.com/firecrownpro/widgetbook
issue_tracker: https://github.com/firecrownpro/widgetbook/issues 
# documentation: https://firecrown.pro 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  vector_math: ^2.1.0
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  assets:
    - google_fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: google_fonts/Nunito-Black.ttf
        - asset: google_fonts/Nunito-BlackItalic.ttf
        - asset: google_fonts/Nunito-Bold.ttf
        - asset: google_fonts/Nunito-BoldItalic.ttf
        - asset: google_fonts/Nunito-ExtraBold.ttf
        - asset: google_fonts/Nunito-ExtraBoldItalic.ttf
        - asset: google_fonts/Nunito-ExtraLight.ttf
        - asset: google_fonts/Nunito-ExtraLightItalic.ttf
        - asset: google_fonts/Nunito-Italic.ttf
        - asset: google_fonts/Nunito-Light.ttf
        - asset: google_fonts/Nunito-LightItalic.ttf
        - asset: google_fonts/Nunito-Regular.ttf
        - asset: google_fonts/Nunito-SemiBold.ttf
        - asset: google_fonts/Nunito-SemiBoldItalic.ttf

