builders:
  theme_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["themeBuilder"]
    build_extensions: { ".dart": [".theme.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  locales_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["localesBuilder"]
    build_extensions: { ".dart": [".locales.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  localizatio_delegates_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["localizationDelegatesBuilder"]
    build_extensions: { ".dart": [".delegates.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  story_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["storyBuilder"]
    build_extensions: { ".dart": [".story.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  device_frame_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["deviceFrameBuilder"]
    build_extensions: { ".dart": [".deviceframebuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  localization_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["localizationBuilder"]
    build_extensions: { ".dart": [".localizationbuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  scaffold_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["scaffoldBuilder"]
    build_extensions: { ".dart": [".scaffoldbuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  theme_resolver_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["themeResolverBuilder"]
    build_extensions: { ".dart": [".themebuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  use_case_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["useCaseBuilder"]
    build_extensions: { ".dart": [".usecasebuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  widgetbook_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["widgetbookBuilder"]
    build_extensions: { ".dart": [".widgetbook.dart"] }
    auto_apply: dependents
    build_to: source