builders:
  theme_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["themeBuilder"]
    build_extensions: { ".dart": [".theme.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  locales_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["localesBuilder"]
    build_extensions: { ".dart": [".ocales.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  story_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["storyBuilder"]
    build_extensions: { ".dart": [".story.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache
  widgetbook_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["widgetbookBuilder"]
    build_extensions: { ".dart": [".widgetbook.dart"] }
    auto_apply: dependents
    build_to: source