on: [ pull_request ]
name: Build (MacOS)
jobs:
  build:
    name: Build
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: subosito/flutter-action@v1
      with:
        channel: stable
    - name: Enable MacOS desktop support
      run: flutter config --enable-macos-desktop
    - run: flutter pub get
    - run: |
        cd meal_app
        flutter pub get
    - run: | 
        cd meal_app
        flutter build macos -t stories/main.dart
    - name: Create tar archive
      run: |
        cd meal_app/build/macos/Build/Products/Release
    - uses: actions/upload-artifact@v2
      with:
        name: AppMacOS
        path: meal_app/build/macos/Build/Products/Release/app.tar.gz
        retention-days: 3
        if-no-files-found: error