on:
  push:
    branches:
      - main
name: deploy-example
jobs:
  build-web:
    defaults:
      run:
        working-directory: examples/widgetbook_example
    name: build web
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.0'
        channel: stable

    - run: flutter pub get
    - run: | 
        flutter build web -t widgetbook/main.dart

    - name: Authenticate Service Account
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.STORAGE_SERVICE_ACCOUNT }}

    - name: Upload folder
      uses: google-github-actions/upload-cloud-storage@v0.4.0
      with:
        path: examples/widgetbook_example/build/web
        destination: demo.widgetbook.io
        parent: false