on: 
  pull_request:
    paths:
      - "examples/**"
      - "packages/widgetbook/**"
      - ".github/workflows/example.yaml"
name: example 
jobs:
  build:
    defaults:
      run:
        working-directory: examples/widgetbook_example
    name: build macOS
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Flutter version
      run: flutter --version

    - name: Enable MacOS desktop support
      run: flutter config --enable-macos-desktop

    - name: Enable melos
      run: flutter pub global activate melos

    - name: Get packages 
      run: melos bootstrap

    - name: Build
      run: | 
        flutter build macos -t widgetbook/main.dart

    - name: Create tar archive
      run: |
        cd build/macos/Build/Products/Release
        tar -cf app.tar.gz widgetbook_example.app

    - uses: actions/upload-artifact@v2
      with:
        name: AppMacOS
        path: examples/widgetbook_example/build/macos/Build/Products/Release/app.tar.gz
        retention-days: 3
        if-no-files-found: error