on: 
  pull_request:
    paths:
      - "examples/**"
      - "packages/widgetbook/**"
      - ".github/workflows/example.yaml"
name: example 
jobs:
  build:
    defaults:
      run:
        working-directory: examples/widgetbook_example
    name: build macOS
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: subosito/flutter-action@v1
      with:
        channel: stable
    - name: Enable MacOS desktop support
      run: flutter config --enable-macos-desktop
    - run: flutter pub get
    - run: | 
        flutter build macos -t widgetbook/main.dart
    - name: Create tar archive
      run: |
        cd build/macos/Build/Products/Release
        tar -cf app.tar.gz meal_app.app

    - uses: actions/upload-artifact@v2
      with:
        name: AppMacOS
        path: examples/widgetbook_example/build/macos/Build/Products/Release/app.tar.gz
        retention-days: 3
        if-no-files-found: error

  build-web:
    defaults:
      run:
        working-directory: examples/widgetbook_example
    name: build web
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: subosito/flutter-action@v1
      with:
        channel: stable

    - run: flutter pub get
    - run: | 
        flutter build web -t widgetbook/main.dart

    - name: Authenticate Service Account
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.STORAGE_SERVICE_ACCOUNT }}

    - name: Upload folder
      uses: google-github-actions/upload-cloud-storage@v0.4.0
      with:
        path: examples/widgetbook_example/build/web
        destination: demo.widgetbook.io
        parent: false