on: 
  pull_request:
    paths:
      - "packages/widgetbook/**"
      - ".github/workflows/unit-test.yaml"
name: Unit test (MacOS)
jobs:
  build:
    defaults:
      run:
        working-directory: packages/widgetbook
    name: Unit test
    runs-on: ubunutu-latest 
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: flutter pub get
    - run: flutter test --coverage