on: 
  pull_request:
    paths:
      - "packages/widgetbook_models/**"
      - ".github/workflows/widgetbook-models.yaml"
  push:
    branches:
      - main
name: widgetbook_models
jobs:
  test:
    name: test
    defaults:
      run:
        working-directory: packages/widgetbook_models
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup dart
      uses: dart-lang/setup-dart@v1

    - name: Get packages 
      run: pub get

    - name: Run Tests
      run: |
        pub global activate test_coverage
        export PATH=$PATH:$HOME/.pub-cache/bin
        test_coverage

    - name: Check Code Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
      with:
        path: packages/widgetbook_models/coverage/lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./packages/widgetbook_models/coverage/

  code-quality:
    defaults:
      run:
        working-directory: packages/widgetbook_models
    name: code quality
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: dart-lang/setup-dart@v1

    - name: Get packages 
      run: dart pub get
    - name: Run analyze
      run: dart analyze